// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package ollama

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	ProcessorConfigModel  = "model"
	ProcessorConfigPrompt = "prompt"
	ProcessorConfigUrl    = "url"
)

func (ProcessorConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ProcessorConfigModel: {
			Default:     "llama3.2",
			Description: "Model is the name of the model used with ollama",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ProcessorConfigPrompt: {
			Default:     "",
			Description: "Prompt is the prompt to pass into ollama to tranform the data",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ProcessorConfigUrl: {
			Default:     "",
			Description: "OllamaURL is the url to the ollama instance",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
